### ISSUE TITLE
Share a teacher's view with students

### ISSUE THREAD

**Issue by F0urchette** [git4school/git4school-visu#109]
**Description**

As a teacher
I want share my current view to my students
So that they can evaluate their progress

**Tasks**

- [ ] Check if we can get a repository owner email with Github API
- [ ] Check if the owner of a generated repository with Github Classroom is the student and not the teacher
- [ ] Check if we can exclude commits with class-transformer according to a property

**Hints**

Activity diagram
![activitydg](https://user-images.githubusercontent.com/16985364/121873894-225e4280-cd07-11eb-86ab-c912e252ddb8.png)

- An icon will mark the assignment in *view only* mode
- The boolean identifying a *view only* assignment will be reported to all the repositories for technical purposes
- It will be necessary to be able to load the *view only* assignments from the database with the commits
