### ISSUE TITLE
Use repositories from other forges than Github (Gitlab)

### ISSUE THREAD

**Issue by F0urchette** [git4school/git4school-visu#114]
**Description**

We need to be able to manage repositories from Gitlab, as well as from hosted Gitlab instances

**Tasks**

- [ ] Login to Gitlab
- [ ] Filter assignments by the forge used to connect
- [ ] API requests to retrieve commits from Gitlab
- [ ] Login settings (to disconnect or connect directly to another forge)
- [ ] Space to add a hosted forge in the homepage

**Hints**

- Here is the [wireframe](https://app.mockplus.com/run/rp/PmtQt5IwtegJ/cw28PQZSazPZ/2FWlgi9D0QTS?ps=0&ha=1&la=0&fc=1&out=1)
- First priority is the connection with Gitlab.com, then with the hosted instances
