### ISSUE TITLE
Default sorting of the assignment list

### ISSUE THREAD

**Issue by F0urchette** [git4school/git4school-visu#84]
**Description**

As a user
I want my assignments to be sorted by their last modification date
So that I can easily find the assignments I last worked with

**Tasks**

- [x] Add the last modification date in the assignment model.
- [x] Update this date each time the assignment is modified.
- [x] Add the column displaying this date in the list of assignments
- [x] Sort by default the list with this date

**Hints**

The sorting part should be easily done with [ngx-datatable sorting](https://github.com/swimlane/ngx-datatable/blob/master/src/app/sorting/sorting-default.component.ts)
